import marimo

__generated_with = "0.24.0"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    This notebook reviews the load calibration parameter sweep results. These results can be regenerated by running the `load_calibrate.py` as a script instead of loading it as a module.
    """)
    return


@app.cell
def _(mo, pd):
    def read_data():
        data = pd.read_csv("load_calibrate.csv")
        return data

    get_data,set_data = mo.state(read_data())

    def reload(*args):
        set_data(read_data())

    return get_data, reload


@app.cell
def _(mo):
    axis_options = ["gamma","mu","lam"]
    x_ui = mo.ui.radio(options=axis_options,label="X-axis:",inline=True,value="gamma")
    return axis_options, x_ui


@app.cell
def _(axis_options, mo, x_ui):
    _options = list(set(axis_options) - set([x_ui.value]))
    y_ui = mo.ui.radio(options=_options,label="Y-axis:",inline=True,value=_options[0])
    return (y_ui,)


@app.cell
def _(get_data, mo):
    _options = sorted(set(get_data().columns) - {"gamma","mu","lam","eps","time","status"})
    value_ui = mo.ui.dropdown(options=_options,label="Value:",value=_options[0])
    return (value_ui,)


@app.cell
def _(mo, reload):
    reload_ui = mo.ui.button(label="Reload",on_click=reload)
    return (reload_ui,)


@app.cell
def _(reload_ui):
    reload_ui.value
    return


@app.cell
def _(mo, reload_ui, value_ui, x_ui, y_ui):
    mo.hstack([x_ui,y_ui,value_ui,reload_ui])
    return


@app.cell
def _(get_data, mo, x_ui, y_ui):
    slider = list({"gamma","mu","lam"}-set([x_ui.value,y_ui.value]))[0]
    slider_ui = mo.ui.slider(steps=get_data()[slider].to_list(),label=slider,show_value=True)
    slider_ui
    return slider, slider_ui


@app.cell
def _(alt, get_data, mo, slider, slider_ui, value_ui, x_ui, y_ui):
    # replace _df with your data source
    _data = get_data()[get_data()[slider]==slider_ui.value]
    _plot = alt.Chart(_data).mark_rect().encode(
        x=alt.X(field=x_ui.value, type='nominal', sort='ascending'),
        y=alt.Y(field=y_ui.value, type='nominal', sort='descending'),
        color=alt.Color(field=value_ui.value, type='quantitative'),
        tooltip=[
            alt.Tooltip(field=x_ui.value, format=',.2f'),
            alt.Tooltip(field=y_ui.value, format=',.2f'),
            alt.Tooltip(field=value_ui.value, format=',.2f')
        ]
    ).properties(
        height=500,
        width='container',
        config={
            'axis': {
                'grid': False
            }
        }
    )
    _data = mo.ui.table(get_data().round(6))
    mo.ui.tabs({
        "Plot": _plot,
        "Data": _data,
    })
    return


@app.cell
def _():
    import marimo as mo
    import numpy as np
    import pandas as pd
    import IPython
    import altair as alt

    return alt, mo, pd


if __name__ == "__main__":
    app.run()
